### ISSUE TITLE
import fails on python 3.7 in linux

### ISSUE THREAD

**Issue by dragonwit** [petamas/oslex#1]
Hello!

I try to import oslex version 0.1.2 on python 3.7.16 in linux and this is the result:

```
>>> import oslex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/someuser/.local/lib/python3.7/site-packages/oslex/__init__.py", line 50, in <module>
    def split(s: str) -> list[str]:
TypeError: 'type' object is not subscriptable
```

Not sure, but maybe using **typing.List** instead of **list** would fix it?

See here: [typing.List](https://docs.python.org/3.7/library/typing.html#typing.List)

**Comment by petamas** [comment]
Hi @dragonwit,

sorry for not noticing this issue earlier, it seems like my notification settings for this repository are not set up as they should.

You're absolutely right, and luckily @YUKI2eN3e has already opened a PR for fixing this. I'll cut a release containing the fix over the weekend.
